---
title: "R Markdown Activity - Week 4"
subtitle: "An implementation in R Markdown using Tufte Template"
author: "Aboli Moroney"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: datascience.bib
link-citations: yes
---

```{r setup, eval = TRUE, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
# Setting up a chunk with 3+ setting
knitr::opts_chunk$set(tidy = FALSE, 
                      cache.extra = packageVersion('tufte'), 
                      cache.comments = FALSE,
                      collapse = TRUE,
                      echo = TRUE,
                      warning = TRUE,
                      message = TRUE)
options(htmltools.dir.version = FALSE)
knitr::read_chunk("externalRcode.R")
```

# Starwars Plot
``` {r starwars-plot, fig.cap = "A scatter plot using Starwars data"}
library(tidyverse)

starwars %>%
  filter(species == "Human") %>%
  ggplot()+
  aes(x = height,
      y = mass) +
      geom_point()
```

# Starwars Table
```{r starwars-tbl}
starwars %>%
  filter(species == "Human") %>%
  select(name,
  height,
  mass,
  homeworld) %>%
  knitr::kable(caption = "A table using Starwars data")
```

# References Cited

@van2016data has a good research paper on Data Science in Action.

@stodden2018enabling says useful things about...

# External R Code

```{r set-up-and-print-the-data, eval = TRUE, echo = TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::read_chunk("externalRcode.R")
```

```{r RunCodeChunkShowAll, echo = TRUE}
source('externalRcode.R')
```



